# Generated by Django 3.1.4 on 2020-12-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveField(
            model_name='bookappointment',
            name='booking_date',
        ),
        migrations.AddField(
            model_name='bookappointment',
            name='appointment_date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
